from tkinter import *
raizhija=Tk()
#raizhija=Toplevel()
raizhija.title("Consulta de Vividores")
raizhija.iconbitmap("C:/Users/aurelio/Desktop/phyton_Xto/recursos/Imagenes/cxto.ico")
raizhija.geometry("1000x260")
conter=Frame(raizhija)
conter.pack()
lbv=Label(conter,text="Buscar por nombre de vividor")
lbv.pack(side=LEFT)
btnBush=Button(conter,text="Buscar")
btnBush.pack(side=RIGHT)
txtbN=Entry(conter)
txtbN.pack(side=RIGHT)
contendorB=Frame(raizhija)
contendorB.pack()
btnCont=Button(contendorB,text="contar")
btnCont.pack(side=LEFT)
txtnum=Entry(contendorB,state="disabled")
txtnum.pack(side=RIGHT)
lbn=Label(contendorB,text="N° vividores:  ")
lbn.pack(side=RIGHT)
contenerdorTabla=Frame(raizhija)
contenerdorTabla.pack()
Tabla=Text(contenerdorTabla,width=100,height=3)
Tabla.pack()
raizhija.mainloop()